--Creates the OMTRTA database and a new user kajal.

DROP DATABASE IF EXISTS OMTRTA;
CREATE DATABASE OMTRTA;
USE OMTRTA;

DROP USER IF EXISTS kajal;
CREATE USER kajal IDENTIFIED BY 'dawson';
GRANT ALL ON OMTRTA.* TO kajal;

FLUSH PRIVILEGES;
